services:
  app:
    build: .
    container_name: proyecto2025-be-app
    env_file: .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
      - mongo-db
    networks:
      - flashcardsnet

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - flashcardsnet

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - flashcardsnet


volumes:
  mysql_data:
    driver: local
  mongo_data:
    driver: local

networks:
  flashcardsnet:
    name: flashcardsnet