server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flashcards
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
    logging:
      level:
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    mongodb:
      uri: mongodb://localhost:27017/flashcards
      auto-index-creation: true
llm:
  url: https://busy-smooth-sunbeam.ngrok-free.app
  auth: Basic Z2VtbWEzOkxvc1BpYml0b3NEZUxhVW5zYW1NYW5kYW4u
  logRequests: true
  logResponses: true