server:
  port: ${API_PORT:8080}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
    logging:
      level:
        org.hibernate.SQL: INFO
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      auto-index-creation: true

llm:
  apiKey: ${OPENAI_API_KEY}
  modelName: gpt-4o-mini
  logRequests: false
  logResponses: false

api:
  preguntas:
    cantidad: 5

logging:
  level:
    root: INFO
    org.springframework: WARN

jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: ${JWT_EXPIRATION}