server:
  port: ${API_PORT:8080}

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: admin
    password: admin
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
llm:
  url: https://busy-smooth-sunbeam.ngrok-free.app
  auth: Basic Z2VtbWEzOkxvc1BpYml0b3NEZUxhVW5zYW1NYW5kYW4u
  logRequests: true
  logResponses: true