spring:
  profiles:
    active: dev
  config:
      import: optional:file:.env[.properties]


server:
  servlet:
    context-path: /api/v1

mercadopago:
  accessToken: ${MP_ACCESS_TOKEN}
  feDomain: ${FE_DOMAIN}
